import { Router } from 'express';
import healthRoutes from '../modules/health/health.routes';
import authRoutes from '../modules/auth/auth.routes';
import userRoutes from '../modules/users/user.routes';
import onboardingRoutes from '../modules/onboarding/onboarding.routes';
import categoryRoutes from '../modules/categories/category.routes';
import geoRoutes from '../modules/geo/geo.routes';
import productRoutes from '../modules/products/product.routes';
import cartRoutes from '../modules/cart/cart.routes';
import orderRoutes from '../modules/orders/order.routes';
import paymentRoutes from '../modules/payments/payment.routes';
import savingsRoutes from '../modules/savings/savings.routes';
import earningsRoutes from '../modules/earnings/earnings.routes';
import b2bRoutes from '../modules/b2b/b2b.routes';
import shopRoutes from '../modules/shops/shop.routes';
import deliveryRoutes from '../modules/delivery/delivery.routes';
import commissionRoutes from '../modules/commission/commission.routes';
import couponRoutes from '../modules/coupons/coupon.routes';
import marketPriceRoutes from '../modules/market-prices/market-price.routes';
import adminSystemRoutes from '../modules/admin-system/admin-system.routes';
import cmsRoutes from '../modules/cms/cms.routes';
import notificationRoutes from '../modules/notifications/notification.routes';
import disputeRoutes from '../modules/disputes/dispute.routes';
import analyticsRoutes from '../modules/analytics/analytics.routes';
import uploadRoutes from '../modules/upload/upload.routes';

const apiRouter = Router();

apiRouter.use(healthRoutes);
apiRouter.use(authRoutes);
apiRouter.use(userRoutes);
apiRouter.use(onboardingRoutes);
apiRouter.use(categoryRoutes);
apiRouter.use(geoRoutes);
apiRouter.use(productRoutes);
apiRouter.use(cartRoutes);
apiRouter.use(orderRoutes);
apiRouter.use(paymentRoutes);
apiRouter.use(savingsRoutes);
apiRouter.use(earningsRoutes);
apiRouter.use(b2bRoutes);
apiRouter.use(shopRoutes);
apiRouter.use(deliveryRoutes);
apiRouter.use(commissionRoutes);
apiRouter.use(couponRoutes);
apiRouter.use(marketPriceRoutes);
apiRouter.use(adminSystemRoutes);
apiRouter.use(cmsRoutes);
apiRouter.use(notificationRoutes);
apiRouter.use(disputeRoutes);
apiRouter.use(analyticsRoutes);
apiRouter.use(uploadRoutes);

export default apiRouter;
